spring:
  datasource:
    url: jdbc:mysql://43.142.151.181:3306/stock?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Dream1226.27!

eureka:
  client:
    serviceUrl:
      defaultZone: http://124.222.217.230:8001/eureka/